### ISSUE TITLE
Add Chart support to workbooks

### ISSUE THREAD

**Issue by msvargas** [jiteshkumawat/oxml.js#2]
I always feel frustrated when I download many Excel packages to create beautiful workbooks, but none create native charts, is it possible to add charts? I am working with [SpreadsheetLight](https://spreadsheetlight.com/) and use OpenXml, it's fast and with many functions, thanks! amazing project

**Comment by jiteshkumawat** [comment]
Hi, This project is still in development, although due to being only developer and some other priority tasks, it got de-prioritize. I have started other project for open xml, i.e. joi, and right now working on opening already saved files in javascript. Will sure work on charts and imaging in this new project.

**Comment by msvargas** [comment]
thanks!
